'use server';
// /app/[locale]/layout.jsx
import { Geist, Geist_Mono } from 'next/font/google';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { getMessages, setRequestLocale } from 'next-intl/server';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export async function generateMetadata({ params }) {
	return {
		title: 'text app',
		description: 'Generated by create next app',
	};
}

export default async function LocaleLayout({ children, params }) {
	const { locale } = await params;
	const messages = await getMessages(); // 所有頁面共用的語系資訊

	// 確保傳入的 "locale" 有效
	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}

	// 處理靜態頁面的語系參數傳遞
	setRequestLocale(locale);

	return (
		<html lang={locale}>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<NextIntlClientProvider locale={locale} messages={messages}>
					{children}
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
