'use server';
// /app/[locale]/layout.jsx
import { Noto_Sans_TC, Alegreya } from 'next/font/google';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { getMessages, getTranslations, setRequestLocale } from 'next-intl/server';

import ThemeProviders from '@/components/common/ThemeProviders';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

// See: https://github.com/kwonoj/swc-plugin-coverage-instrument/issues/199#issuecomment-1463562229
/* istanbul ignore next */
const NotoSansTC = Noto_Sans_TC({
	subsets: ['latin'], // "chinese-traditional" 不可用
	display: 'optional',
});
const AlegreyaFont = Alegreya({
	subsets: ['latin'], // 英文語系字型
	display: 'optional',
});
// latin：拉丁字母，適用於英文和大多數歐洲語言

// export async function generateMetadata({ params }) {
// 	return {
// 		title: 'text app',
// 		description: 'Generated by create next app',
// 	};
// }

export async function generateMetadata({ params }) {
	const { locale } = await params;
	const t = await getTranslations({ locale });
	// 分享至社群上顯示內容，例如 facebook
	const hantOpenGraph = {
		title: t('title'),
		description: '網站描述',
		url: 'url',
		images: [
			{
				url: 'https://sport.kinglyrobot.com/meta/open_graph_image_1200x600.jpg',
				width: 1200,
				height: 600,
				alt: '測試 alt',
			},
		],
		locale: 'zh-Hant-TW',
		type: 'website',
	};

	return {
		title: t('title'),
		openGraph: hantOpenGraph,
	};
}

export default async function LocaleLayout({ children, params }) {
	const { locale } = await params;
	const messages = await getMessages(); // 所有頁面共用的語系資訊

	// 確保傳入的 "locale" 有效
	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}

	// 處理靜態頁面的語系參數傳遞
	setRequestLocale(locale);

	return (
		<NextIntlClientProvider locale={locale} messages={messages}>
			<html lang={locale} className='min-w-[320px]' suppressHydrationWarning>
				<body className={`${NotoSansTC.className} antialiased`}>
					<ThemeProviders>
						<div className='flex min-h-screen max-w-full flex-col'>
							<Header />
							<main className='grow pt-3'>{children}</main>
							<Footer />
						</div>
					</ThemeProviders>
				</body>
			</html>
		</NextIntlClientProvider>
	);
}
