'use server';
// /app/[locale]/layout.jsx
import { Geist, Geist_Mono } from 'next/font/google';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
import { getMessages, getTranslations, setRequestLocale } from 'next-intl/server';
import LanguageSwitcher from '@/components/i18n/LanguageSwitcher';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

// export async function generateMetadata({ params }) {
// 	return {
// 		title: 'text app',
// 		description: 'Generated by create next app',
// 	};
// }

export async function generateMetadata({ params }) {
	const { locale } = await params;
	const t = await getTranslations({ locale });
	// 分享至社群上顯示內容，例如 facebook
	const hantOpenGraph = {
		title: t('title'),
		description: '網站描述',
		url: 'url',
		images: [
			{
				url: 'https://sport.kinglyrobot.com/meta/open_graph_image_1200x600.jpg',
				width: 1200,
				height: 600,
				alt: '測試 alt',
			},
		],
		locale: 'zh-Hant-TW',
		type: 'website',
	};

	return {
		title: t('title'),
		openGraph: hantOpenGraph,
	};
}

export default async function LocaleLayout({ children, params }) {
	const { locale } = await params;
	const messages = await getMessages(); // 所有頁面共用的語系資訊

	// 確保傳入的 "locale" 有效
	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}

	// 處理靜態頁面的語系參數傳遞
	setRequestLocale(locale);

	return (
		<NextIntlClientProvider locale={locale} messages={messages}>
			<html lang={locale} className='min-w-[328px]'>
				<body className={`${geistSans.variable} ${geistMono.variable} mx-auto antialiased`}>
					<div className='flex min-h-screen max-w-full flex-col'>
						<header className='flex items-center justify-center p-3'>
							<LanguageSwitcher />
						</header>
						<main className='grow'>{children}</main>
					</div>
				</body>
			</html>
		</NextIntlClientProvider>
	);
}
